# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jechever <jechever@student.42malaga.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/04/29 12:57:50 by jechever          #+#    #+#              #
#    Updated: 2023/04/29 13:57:46 by jechever         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= libft.a

SRCS	=	ft_isalpha.c \
			ft_isdigit.c \
			ft_isalnum.c \
			ft_isascii.c \
			ft_isprint.c \
			ft_strlen.c \
			ft_strchr.c \
			ft_strrchr.c \
			ft_strncmp.c \
			ft_strlcpy.c \
			ft_strlcat.c \
			ft_bzero.c \
			ft_memset.c \
			ft_memcpy.c \
			ft_memmove.c \
			ft_memchr.c \
			ft_memcmp.c \
			ft_toupper.c \
			ft_tolower.c \
			ft_atoi.c \
			ft_calloc.c \
			ft_strdup.c \
			ft_substr.c \
			ft_strjoin.c \
			ft_strtrim.c \
			ft_split.c \
			ft_itoa.c \
			ft_strmapi.c \
			ft_striteri.c \
			ft_putchar_fd.c \
			ft_putstr_fd.c \
			ft_putendl_fd.c \
			ft_putnbr_fd.c

OBJS	=	$(SRCS:.c=.o)
			
SRCS_B	=	ft_lstsize.c \
			ft_lstadd_front.c \
			ft_lstadd_back.c \
			ft_lstdelone.c \
			ft_lstclear.c \
			ft_lstiter.c \
			ft_lstnew.c \
			ft_lstlast.c \
			ft_lstmap.c

OBJS_B	=	$(SRCS_B:.c=.o)

CC	= gcc
CF	= -Wall -Wextra -Werror -I.
RM	= rm -f

all:	$(NAME)

$(NAME):$(OBJS)
		ar rcs $(NAME) $(OBJS)

$(OBJS):$(SRCS)
		$(CC) $(CF) -c $(SRCS)

bonus:	$(NAME)

$(NAME):$(OBJS_B)
		ar rcs $(NAME) $(OBJS_B)

$(OBJS_B):$(SRCS_B)
		$(CC) $(CF) -c $(SRCS_B)

clean:	$(RM) $(OBJS) $(OBJS_B)

fclean:	clean
		$(RM) $(NAME)

re:		fclean $(NAME)

.PHONY:	all clean fclean re bonus